[theme]
base = "dark"
primaryColor = "#818CF8"
backgroundColor = "#060B18"
secondaryBackgroundColor = "#0D1526"
textColor = "#F0F6FF"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false